// frontend/src/components/Header.vue
<template>
  <header class="fixed top-0 inset-x-0 bg-white/80 backdrop-blur border-b z-40">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-20">





      <div class="flex items-center gap-3 cursor-pointer" @click="$emit('navigate', 'landing')">
        <img src="@/assets/logo.png" alt="Notav" class="h-10 w-auto" />
      </div>




      <div class="flex items-center gap-3">
        <button
          class="hidden sm:inline-flex items-center px-3 py-1.5 text-sm rounded-full border border-gray-200 text-gray-700 hover:bg-gray-50"
          @click="$emit('navigate', 'signup')"
        >
          회원가입
        </button>
        <button
          class="inline-flex items-center px-4 py-2 text-sm font-medium rounded-full bg-brand-600 text-white hover:bg-brand-700"
          @click="$emit('navigate', 'login')"
        >
          로그인
        </button>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
defineProps<{
  currentPage?: "landing" | "login" | "signup" | "dashboard";
}>();

defineEmits<{
  (e: "navigate", page: "landing" | "login" | "signup" | "dashboard"): void;
}>();
</script>

// mockup/src/components/Header.tsx
import { Button } from "./ui/button";

interface HeaderProps {
  onNavigate: (page: 'landing' | 'login' | 'signup') => void;
  currentPage: string;
}

export function Header({ onNavigate, currentPage }: HeaderProps) {
  return (
    <header className="fixed top-0 left-0 right-0 bg-white border-b border-gray-200 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div 
            className="cursor-pointer"
            onClick={() => onNavigate('landing')}
          >
            <h1 className="text-blue-600">노타브</h1>
          </div>
          
          <nav className="hidden md:flex items-center gap-8">
            <a href="#service" className="text-gray-700 hover:text-blue-600 transition-colors">
              서비스 소개
            </a>
            <a href="#features" className="text-gray-700 hover:text-blue-600 transition-colors">
              주요 기능
            </a>
            <a href="#howto" className="text-gray-700 hover:text-blue-600 transition-colors">
              이용 방법
            </a>
          </nav>

          <div className="flex items-center gap-3">
            {currentPage !== 'login' && (
              <Button 
                variant="ghost"
                onClick={() => onNavigate('login')}
                className="text-gray-700"
              >
                로그인
              </Button>
            )}
            {currentPage !== 'signup' && (
              <Button 
                onClick={() => onNavigate('signup')}
                className="bg-blue-600 hover:bg-blue-700 text-white"
              >
                회원가입
              </Button>
            )}
          </div>
        </div>
      </div>
    </header>
  );
}
